title: 今月の物置（仮）
author: 今月の新刊（@skrbcr）

  # It will appear in your document head meta (for Google search results) and in your feed.xml site description.
description: >- # this means to ignore newlines until "baseurl:"
  物理＋プログラミング＋その他
baseurl: "/blog"
url: "https://skrbcr.github.io"
twitter_username: skrbcr
github_username:  skrbcr

permalink: /:categories/:title

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]

theme: minima
plugins:
  - jemoji
  - jekyll-feed

minima:
  date_format: "%Y年%m月%d日"
