title: Diary of skrbcr
  
  # It will appear in your document head meta (for Google search results) and in your feed.xml site description.
description: >- # this means to ignore newlines until "baseurl:"
  物理＋プログラミング＋その他
#baseurl: "/diary" # the subpath of your site, e.g. /blog
#url: "https://skrbcr.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: skrbcr
github_username:  skrbcr

# Build settings
theme: minima
plugins:
  - jemoji
  - jekyll-feed
