title: 今月の物置
author: 今月の新刊（@skrbcr）

  # It will appear in your document head meta (for Google search results) and in your feed.xml site description.
description: >- # this means to ignore newlines until "baseurl:"
  物理＋プログラミング＋その他
baseurl: "/blog"
url: "https://skrbcr.github.io"
twitter_username: skrbcr
github_username:  skrbcr

lang: ja

# destination: docs

permalink: /:categories/:title

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]

theme: minima
plugins:
  - jemoji
  - jekyll-feed
  # - jekyll-paginate
  - jekyll-paginate-v2

minima:
  date_format: "%Y年%m月%d日"

# jekyll-paginate
# paginate: 5
# paginate_path: "/blog/page:num/"

# jekyll-paginate-v2
pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 5
  permalink: /page/:num/
  sort_field: 'date'
  sort_reverse: true
